### ISSUE TITLE
TypeError: Cannot read property 'shadowRoot' of null

### ISSUE THREAD

**Issue by suyogn** [adamlacombe/Shadow-DOM-inject-styles#1]
I used shadow-DOM-inject-styles as follow:
constructor(private el: ElementRef) {
    const tabbar = this.el.nativeElement.querySelector('ion-tabs > ion-tabbar') as HTMLElement;
    const styles = `
      .tabbar-background {
        background: red !important;;
      }`;
    injectStyles(tabbar, '.tabbar-background', styles);
  }
but i got an error as below:
TypeError: Cannot read property 'shadowRoot' of null

**Comment by frontendraiden** [comment]
mee too

**Comment by adamlacombe** [comment]
Can you create a repo where I could replicate the issue you're having?

Thanks

**Comment by binhnguyen1368** [comment]
![image](https://user-images.githubusercontent.com/36718785/47598415-7cc6fb00-d9c5-11e8-8e1e-b9482d6aff52.png)
`const styles ='
      .layout-icon-top {
        height: 50px !important;
      }
    ';
    const tabbar = this.el.nativeElement.querySelector('ion-tabs > ion-tabbar') as HTMLElement;
    injectStyles(tabbar, '.tabs-inner', styles);`

I have same issue :(

**Comment by binhnguyen1368** [comment]
![image](https://user-images.githubusercontent.com/36718785/47603703-19b38380-da1a-11e8-92af-5a3e4a14fbeb.png)

**Comment by binhnguyen1368** [comment]
![image](https://user-images.githubusercontent.com/36718785/47603711-2cc65380-da1a-11e8-90c6-2dc37fc80c25.png)

**Comment by adamlacombe** [comment]
If you're trying to use this package with Ionic/Angular you'll need to wait until the dom renders. Try using *injectStyles()* inside *ionViewDidEnter()*.

Here's an example using Angular/Ionic:

```bash
git clone https://github.com/ionic-team/ionic-conference-app.git && cd ionic-conference-app && npm install && npm install shadow-dom-inject-styles
```

**src/app/pages/tutorial/tutorial.ts**
```typescript
import { Component, ViewChild, ViewEncapsulation, ElementRef } from '@angular/core';
import { Router } from '@angular/router';
import {injectStyles} from 'shadow-dom-inject-styles';
import { MenuController, Slides } from '@ionic/angular';

import { Storage } from '@ionic/storage';

@Component({
  selector: 'page-tutorial',
  templateUrl: 'tutorial.html',
  styleUrls: ['./tutorial.scss'],
  encapsulation: ViewEncapsulation.None
})
export class TutorialPage {
  showSkip = true;

  @ViewChild('slides') slides: Slides;

  constructor(
    public menu: MenuController,
    public router: Router,
    public storage: Storage,
    private el: ElementRef
  ) {}

  startApp() {
    this.router
      .navigateByUrl('/app/tabs/(schedule:schedule)')
      .then(() => this.storage.set('ion_did_tutorial', 'true'));
  }

  onSlideChangeStart(event) {
    event.target.isEnd().then(isEnd => {
      this.showSkip = !isEnd;
    });
  }

  ionViewWillEnter() {
    this.storage.get('ion_did_tutorial').then(res => {
      if (res === true) {
        this.router.navigateByUrl('/app/tabs/(schedule:schedule)');
      }
    });

    this.menu.enable(false);
  }

  ionViewDidEnter() {
    const styles =' .toolbar-background {background: red !important; } '; 
    const tabbar = this.el.nativeElement.querySelector('ion-toolbar') as HTMLElement; 
    injectStyles(tabbar, '.toolbar-background', styles);
  }

  ionViewDidLeave() {
    // enable the root left menu when leaving the tutorial page
    this.menu.enable(true);
  }
}

```


**src/app/pages/tabs-page/tabs-page.ts**
```typescript
import { injectStyles } from 'shadow-dom-inject-styles';
import { Component, ElementRef } from '@angular/core';

@Component({
  templateUrl: 'tabs-page.html'
})
export class TabsPage {

  constructor(private el: ElementRef) {
    
  }

  ionViewDidEnter() {
    const tabbar = this.el.nativeElement.querySelector('ion-tabs > ion-tabbar') as HTMLElement;
    const styles = '.tabbar-background { background: red !important; }';
    injectStyles(tabbar, '.tabbar-background', styles);
  }

}

```

Run:
```bash
npm run start
```

**Comment by binhnguyen1368** [comment]
@adamlacombe Thankiu so much <3

**Comment by vitaliyhayda** [comment]
Please add this to README... I spent hours trying various ways, but all I needed was **injectStyles** inside **ionViewDidEnter** as in the comment above
