### ISSUE TITLE
Typescript example for multi DOM object

### ISSUE THREAD

**Issue by sonicwong** [adamlacombe/Shadow-DOM-inject-styles#3]
Maybe someone need this:

```
[].forEach.call(document.querySelectorAll('ion-button'), function(div) {
      const styles = `
      button {
        background: red !important;
      }
      `;
      injectStyles(div, 'button', styles);
    });
```

**Comment by santiagovasquez** [comment]
> Maybe someone need this:
> 
> ```
> [].forEach.call(document.querySelectorAll('ion-button'), function(div) {
>       const styles = `
>       button {
>         background: red !important;
>       }
>       `;
>       injectStyles(div, 'button', styles);
>     });
> ```

which contains this variable this.el ?

**Comment by sonicwong** [comment]
@santiagovasquez
I run this code inside ionviewdidload for ionic 4 app.
