### ISSUE TITLE
big bug

### ISSUE THREAD

**Issue by johnjackson** [adamlacombe/Shadow-DOM-inject-styles#5]
there is a bug: if there isn't any <style> tag in the shadowRootElement, this function can't work, because it use forEach of style tag elements.

**Comment by cns-dan** [comment]
Duplicate of #4

**Comment by adamlacombe** [comment]
Resolved in https://github.com/adamlacombe/Shadow-DOM-inject-styles/pull/6

Try version 1.0.3
